name: Job Output Example
on: [push]
env: # اینجا برای همه جاب ها است
  MOMGO_URL: my_dn # معمولا اسم دی بی ثابت است    

jobs:
  job1:
    env: # اینجا برای این جاب است
      MOMGO_PASS: my_dn
      PORT: 3000  
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache deoendencies
        uses: actions/chache@v3 # پوشه .npm رو توی سرور های گیتهاب ذخیره میکنه تا توی جا های بعدی از اون استفاده کنه
        with:
          path: ~/.npm  # توی لینوکس اینجا ذخیره میشه
          key: deps-node-modules-${{ hashFiles('**/packages-lock-.json') }} # بر اساس هر چی این فایل رو پیددا کرده یک چیزی هش شده درست میکنه
      - name: install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-n http:///127.0.0.1:$PORT  # اینجا از پورت استفاده میکنیم که توی متغیر محیطی تعریف کردیم
      -name: Echo information
        run: echo ${{ env.MOMGO_URL }} #اینجوری هم میشه 