name: First
on: workflow_dispatch // manualy start
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello"
      - name: Pritn goodby
        run: echo "goofby"
