name: Test
#---------
# simple
on: push
# on: [push, workflow_dispatch] multiple trigger
#--------
on:
  pull_request: # first trigger
    types:
      - opened
      - edited
    branches:
      - main
      - dev
#--------
  workflow_dispatch: # second trigger
#--------
  push: # third trigger 
    branches: 
      - main # just push on main branch
      - 'dev-*'
      - 'feat/**' # feat/new feat/new/new
    paths   :
      - '**js'
    paths-ignore:
      - '.github/workflows/*'  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        use: action/checkout@v3
      - name: Install nodejs 
        use: action/setup-nodejs@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm i
      - name: Test
        run: echo "npm run test!!"
  build:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        use: action/checkout@v3
      - name: Install nodejs 
        use: action/setup-nodejs@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: Upload artifacts 
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: |
            dist
            package.json
          # path: dist //if one path         
  deployment:
    needs: build
    # needs: [test,test2]
    runs-on: ubuntu-latest
      steps:
        - name: Get build artifacts 
          uses: actions/download-artifact@v3
          with:
            name: dist-files
        - name: Show files
          run: ls    
        - name: deployment
          run: echo "deploymen..."



